### PR TITLE
【OSCP】在 YACL 上支持基于 OT 的 Private Set Union 算法

### LINKED ISSUE #98: 在 YACL 上支持基于 OT 的 Private Set Union 算法
> 此 ISSUE 为 [隐语开源共建计划（SecretFlow Open Source Contribution Plan，简称 SF OSCP）第三期](https://github.com/orgs/secretflow/discussions/1007)任务 ISSUE，欢迎社区开发者参与共建～
> 若有感兴趣想要认领的任务，但还未报名，辛苦先完成[报名](https://www.wjx.top/vm/QKio0dq.aspx#)进行哈～

## 任务介绍
- 任务名称：在 YACL 上支持基于 OT 的 Private Set Union 算法
- 技术方向：YACL，密码学，PSU，OPRF
- 任务难度：进阶🌟🌟

## 详细要求
- 安全性：
  - 遵循论文中的协议实现
  - if possible，默认安全强度为 128 bit
- 功能性：
  - 支持输入值为 uint128_t vector 的 PSU 基础计算
  - 支持相应参数调整
-  代码规范：
  - C++ 代码需要遵循 Google C++ style guidelines，除了以下几条 exceptions
    - Exceptions are allowed and encouraged where appropriate.
    - Header guards should use #pragma once.
    - Adopt camelBack for function names.
    - Use fixed width integer types whenever possible.
    - Avoid using size_t on interface APIs.
  - 可使用 clangd 进行代码格式化
  - 可使用 cpplint 检查格式
- 提交说明：关联该 issue 并提交代码至 https://github.com/secretflow/yacl/tree/main/yacl/crypto/primitives/sse

## 能力要求
- 熟悉密码学以及隐私计算原语
- 熟悉 C++ 以及性能优化

## 参考内容
- [原始论文](https://eprint.iacr.org/2019/776.pdf)
- [其他代码库实现](https://github.com/osu-crypto/PSU)

### PR DESCRIPTION
**Pull request by zhangwfjh**
Fixed #98

### CODE REVIEW

File: yacl/crypto/primitives/psu/krtw19_psu.h [hunk 1]
```diff
@@ -0,0 +1,34 @@
...
+
+#pragma once
+
+#include <memory>
+#include <vector>
+
+#include "yacl/base/int128.h"
+#include "yacl/link/link.h"
+
+namespace yacl::crypto::psu {
```
Comment (Jamie-Cui) [inline yacl/crypto/primitives/psu/krtw19_psu.h:23]: Hi, can you make this namespace `yacl::crypto`? Thx

File: yacl/crypto/primitives/psu/krtw19_psu.cc [hunk 2]
```diff
@@ -0,0 +1,241 @@
...
+
+constexpr size_t NUM_BASE_OT{128ul};
+constexpr size_t NUM_INKP_OT{512ul};
+
+static std::random_device rd;
+static std::mt19937 gen(rd());
+
+struct HashU128 {
+  size_t operator()(const uint128_t& x) const {
+    return yacl::math::UniversalHash<uint128_t>(1, {x});
```
Comment (Jamie-Cui) [inline yacl/crypto/primitives/psu/krtw19_psu.cc:51]: P0: Please use the collision-resistent hash function (Blake3, Sha2, ...), which are defined in `yacl/crypto/base/hash/hash_utils.h`.

FYI, the universal hash is considered weaker (but faster) than the CRHash, see: https://crypto.stackexchange.com/a/88247/61581 for more discussions of the security model

File: yacl/crypto/primitives/psu/krtw19_psu.cc [hunk 3]
```diff
@@ -0,0 +1,241 @@
...
+  }
+};
+
+yacl::Buffer Serialize(uint64_t num) {
```
Comment (Jamie-Cui) [inline yacl/crypto/primitives/psu/krtw19_psu.cc:55]: There's `Buffer SerializeInt128(int128_t v)` in `yacl/utils/serialize.h`, you may use that function or add `Buffer SerializeUint64(uint64_t v)` in that file.

File: yacl/crypto/primitives/psu/krtw19_psu.h [hunk 4]
```diff
@@ -0,0 +1,34 @@
...
+
+// Scalable Private Set Union from Symmetric-Key Techniques
+// https://eprint.iacr.org/2019/776.pdf
+
+void KrtwPsuSend(std::shared_ptr<yacl::link::Context>,
```
Comment (Jamie-Cui) [inline yacl/crypto/primitives/psu/krtw19_psu.h:28]: P2: it's recommended to use `const std::shared_ptr<link::Context>& lctx`

**Review by Jamie-Cui — CHANGES_REQUESTED** [review]
Please make changes to this PR according~ thanks

File: yacl/crypto/primitives/psu/krtw19_psu.cc [hunk 5]
```diff
@@ -0,0 +1,241 @@
...
+    return ret;
+  }
+};
+
+auto HashInputs(const std::vector<uint128_t>& elem_hashes, size_t count) {
+  size_t num_bins = std::ceil(count * ZETA);
+  std::vector<std::vector<uint128_t>> hashing(num_bins);
+  for (auto elem : elem_hashes) {
+    auto hash = U128Hasher{}(elem);
+    hashing[hash % num_bins].push_back(elem);
```
Comment (Jamie-Cui) [inline yacl/crypto/primitives/psu/krtw19_psu.cc:70]: You can just use `uint128_t Blake3_128(ByteContainerView data);` like

```
for(auto elem : elem_hashes){
   auto hash = Blake3_128(&elem, sizeof(uint128_t));
}
```

File: yacl/crypto/primitives/psu/krtw19_psu.cc [hunk 6]
```diff
@@ -0,0 +1,241 @@
...
+      auto buf = ctx->Recv(ctx->PrevRank(), "Receive coefficients");
+      std::memcpy(coeffs.data(), buf.data(), buf.size());
+      auto y = Evaluate(coeffs, U128Hasher::CRHash(elem)) ^ eval;
+      ctx->SendAsync(ctx->NextRank(), SerializeUint128(y), "Send evaluation");
+    }
+  }
+
+  // Step 4. Send new elements through OT
+  std::vector<std::array<uint128_t, 2>> keys(num_ot);
+  choice = RandBits(NUM_BASE_OT);
```
Comment (Jamie-Cui) [inline yacl/crypto/primitives/psu/krtw19_psu.cc:158]: P1: Use `SecureRandBits`

**Review by Jamie-Cui — CHANGES_REQUESTED** [review]

File: yacl/crypto/primitives/psu/krtw19_psu.cc (hunk 5 above)
Comment (zhangwfjh) [reply yacl/crypto/primitives/psu/krtw19_psu.cc:70]: Use `Blake` for both hashing index and CRHash?

File: yacl/crypto/primitives/psu/krtw19_psu.h [hunk 7]
```diff
@@ -0,0 +1,34 @@
...
+#include <vector>
+
+#include "yacl/base/int128.h"
+#include "yacl/link/link.h"
+
+namespace yacl::crypto {
+
+// Scalable Private Set Union from Symmetric-Key Techniques
+// https://eprint.iacr.org/2019/776.pdf
+
```
Comment (Jamie-Cui) [inline yacl/crypto/primitives/psu/krtw19_psu.h:27]: We've introduced security parameter declaration for each yacl module, can you add declarations and the submodules?

File: yacl/crypto/primitives/psu/krtw19_psu.cc [hunk 8]
```diff
@@ -0,0 +1,228 @@
...
+constexpr size_t NUM_INKP_OT{512ul};
+
+static std::random_device rd;
+static std::mt19937 gen(rd());
+
+struct U128Hasher {
+  size_t operator()(const uint128_t& x) const {
+    auto hash = Blake3_128({&x, sizeof x});
+    size_t ret;
+    std::memcpy(&ret, &hash, 1);
```
Comment (Jamie-Cui) [inline yacl/crypto/primitives/psu/krtw19_psu.cc:47]: P0: `std::memcpy` will copy just 1 byte, but the bit width of `size_t` is not less than 16 (2 bytes). (since C99)
see: https://en.cppreference.com/w/c/types/size_t

File: yacl/crypto/primitives/psu/krtw19_psu.cc [hunk 9]
```diff
@@ -0,0 +1,228 @@
...
+#include <utility>
+
+#include "yacl/utils/serialize.h"
+
+namespace yacl::crypto {
+
+namespace {
+
+// reference: https://eprint.iacr.org/2019/1234.pdf (Figure 2)
+constexpr float ZETA{0.06f};
```
Comment (Jamie-Cui) [inline yacl/crypto/primitives/psu/krtw19_psu.cc:31]: Style: would you like to rename all `constexpr` var to `kXXXX` (e.g. `ZETA` to `kZeta`), capitalizing only the first letter of each word.

File: yacl/crypto/primitives/psu/krtw19_psu.cc [hunk 10]
```diff
@@ -0,0 +1,228 @@
...
+constexpr size_t BATCH_SIZE{NUM_BINS_PER_BATCH * BIN_SIZE};
+
+constexpr size_t NUM_BASE_OT{128ul};
+constexpr size_t NUM_INKP_OT{512ul};
+
+static std::random_device rd;
+static std::mt19937 gen(rd());
+
+struct U128Hasher {
+  size_t operator()(const uint128_t& x) const {
```
Comment (Jamie-Cui) [inline yacl/crypto/primitives/psu/krtw19_psu.cc:44]: P? `operator()` may be declared `static`, so you can call this as `U128Hasher::operator(x)`. It's okay to use `struct`, but my recommendation is to replace it with a single function, such as `size_t HashToSizeT(uint128_t x)`.

File: yacl/crypto/primitives/psu/krtw19_psu.cc [hunk 11]
```diff
@@ -0,0 +1,228 @@
...
+  auto choice = RandBits(NUM_BASE_OT);
+  auto base_ot = BaseOtRecv(ctx, choice, NUM_BASE_OT);
+  auto store = IknpOtExtSend(ctx, base_ot, NUM_INKP_OT);
+  receiver.Init(ctx, store, num_ot);
+  receiver.SetBatchSize(BATCH_SIZE);
+
+  std::vector<uint128_t> elems;
+  elems.reserve(num_ot);
+  size_t oprf_idx{};
+  for (size_t bin_idx{}; bin_idx != hashing.size(); ++bin_idx) {
```
Comment (Jamie-Cui) [inline yacl/crypto/primitives/psu/krtw19_psu.cc:122]: P? Why not cuckoo hashing?

File: yacl/crypto/primitives/psu/krtw19_psu.cc [hunk 12]
```diff
@@ -0,0 +1,228 @@
...
+    if (bin_idx % NUM_BINS_PER_BATCH == 0) {
+      receiver.SendCorrection(
+          ctx, std::min(BATCH_SIZE, (hashing.size() - bin_idx) * BIN_SIZE));
+    }
+    hashing[bin_idx].resize(BIN_SIZE);
+    std::shuffle(hashing[bin_idx].begin(), hashing[bin_idx].end(), gen);
```
Comment (Jamie-Cui) [inline yacl/crypto/primitives/psu/krtw19_psu.cc:128]: Since `hashing[bin_idx]` contains only hashed values, you may use `std::sort` (faster) instead of `std::shuffle`. Many paper states that hash and sort equals to shuffle assuming hash function is an instantiation of Random Oracle.

File: yacl/crypto/primitives/psu/krtw19_psu.cc (hunk 10 above)
Comment (zhangwfjh) [reply yacl/crypto/primitives/psu/krtw19_psu.cc:44]: [static operator()](https://en.cppreference.com/w/cpp/feature_test#cpp_static_call_operator) is only supported since C++23. The struct here is used as a function object for hasher in `std::unordered_set`. But I could change it to a lambda.

File: yacl/crypto/primitives/psu/krtw19_psu.cc (hunk 11 above)
Comment (zhangwfjh) [reply yacl/crypto/primitives/psu/krtw19_psu.cc:122]: It may reveal the sender's set information. See [Chap 5.4](https://eprint.iacr.org/2019/776.pdf).

**Comment by Jamie-Cui** [comment]
Thanks for you contribution, currently this PR is under security review by our team, this PR will be merged if our security team has no more concerns.

**Comment by zhangwfjh** [comment]
> Could you explain the implementation of the function Interpolate() in yacl/crypto/primitives/psu/krtw19_psu.cc?

The key recursive step is the following
$$\[x^k\](x-x_1) \dotsm (x-x_j) = \[x^k\](x-x_1) \dotsm (x-x_{j-1}) + x_j \cdot \[x^{k-1}\](x-x_1) \dotsm (x-x_{j-1}),$$
where $\[x^k\] p(x)$ represents the $k$-th order coefficient $p_k$ of the polynomial $p(x)=\sum_k p_kx^k$.

**Comment by Jamie-Cui** [comment]
> > Could you explain the implementation of the function Interpolate() in yacl/crypto/primitives/psu/krtw19_psu.cc?
> 
> The key recursive step is the following [xk](x−x1)⋯(x−xj)=[xk−1](x−x1)⋯(x−xj−1)−xj⋅[xk](x−x1)⋯(x−xj−1), where [xk]p(x) represents the k-th order coefficient pk of the polynomial p(x)=∑kpkxk.

Sorry I've been away from work for some time. Can you please explain more details about the codes (or, is there any other references that you can refer your code to? If there is, we may speed up the security-review process and merge this PR). Many thanks. 

Again, sorry for the delay :)

**Comment by zhangwfjh** [comment]
> > > Could you explain the implementation of the function Interpolate() in yacl/crypto/primitives/psu/krtw19_psu.cc?
> > 
> > 
> > The key recursive step is the following [xk](x%E2%88%92x1)⋯(x−xj)=[xk−1](x%E2%88%92x1)⋯(x−xj−1)−xj⋅[xk](x%E2%88%92x1)⋯(x−xj−1), where [xk]p(x) represents the k-th order coefficient pk of the polynomial p(x)=∑kpkxk.
> 
> Sorry I've been away from work for some time. Can you please explain more details about the codes (or, is there any other references that you can refer your code to? If there is, we may speed up the security-review process and merge this PR). Many thanks.
> 
> Again, sorry for the delay :)

The implementation is based on the following formula (w.o. optimization).
image
image

I made some minor changes to the original codes to improve readability.
```cpp
// @param x The x-coordinates of the points.
// @param y The y-coordinates of the points.
// @return The interpolation polynomial L(X) such that L(x[i]) = y[i] for all i.
auto Interpolate(const std::vector<uint64_t>& x,
                 const std::vector<uint64_t>& y) {
  using Poly = std::vector<uint64_t>;
  size_t n{x.size()};
  Poly L(n);  // L(X) = sum_{i=0}^{n-1} y[i] * Li(X)
  for (size_t i{}; i != n; ++i) {
    Poly Li(n);       // Li(X) = num(X) / den
    uint64_t den{1};  // den = ∏_{j≠i} (x[i] - x[j]) = den<n-1>
    Poly num(n);      // num(X) = ∏_{j≠i} (X - x[j]) = num<n-1>(X)
    for (size_t j{}; j != n; ++j) {
      if (x[i] != x[j]) {
        den = GfMul64(den, x[i] ^ x[j]);  // den<j> = den<j-1> * (x[i] - x[j])
        uint64_t num_km1{0};              // num<j-1>[k-1]
        for (size_t k{}; k != n; ++k) {
          // num<j>(X)[k] = (num<j-1>(X) * (X - x[j]))[k]
          //              = (num<j-1>(X) * X)[k] - (num<j-1>(X) * x[j])[k]
          //              = num<j-1>(X)[k-1] - num<j-1>(X)[k] * x[j]
          num_km1 = std::exchange(num[k], num_km1 ^ GfMul64(num[k], x[j]));
        }
      }
    }
    for (size_t k{}; k != n; ++k) {
      Li[k] = GfMul64(num[k], Inv64(den));
      L[k] ^= GfMul64(y[i], Li[k]);
    }
  }
  return L;
}
```

**Review by Jamie-Cui — APPROVED** [review]
LGTM
